INSERT INTO service_entity(description, name, price) VALUES
('Basic hair trim service','Hair Trim',150),
('Advanced hair cutting','Haircut Premium',300),
('Deep conditioning hair spa','Hair Spa Deluxe',600),
('Quick beard shave','Beard Shave',120),
('Premium beard styling','Beard Style Premium',350),
('Classic facial treatment','Facial Classic',650),
('Luxury facial treatment','Facial Luxury',1200),
('Professional hair coloring','Hair Color Premium',1800),
('Hair highlights styling','Hair Highlights',2000),
('Keratin hair treatment','Keratin Treatment',3500),
('Relaxing oil head massage','Oil Head Massage',350),
('Full body spa therapy','Body Spa',4000),
('Luxury body massage','Body Massage',2500),
('Express manicure service','Express Manicure',250),
('Express pedicure service','Express Pedicure',300),
('Full arm waxing treatment','Full Arm Waxing',700),
('Full leg waxing treatment','Full Leg Waxing',900),
('Eyebrow shaping service','Eyebrow Shaping',120),
('Hair wash and blow dry','Hair Wash',200),
('Professional party hairstyle','Party Hairstyle',900);
