name: Run Application (No Tests)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass@word1
          MYSQL_DATABASE: appointment_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppass@word1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Node Dependencies
      run: npm ci

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build Backend
      run: |
        cd online-booking
        chmod +x mvnw
        ./mvnw clean install -DskipTests

    - name: Start Backend
      run: |
        cd online-booking
        nohup ./mvnw spring-boot:run &
        sleep 40

    - name: Wait for Backend
      run: npx wait-on tcp:8081

    - name: Seed Services
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        mysql -h 127.0.0.1 -uroot -ppass@word1 appointment_db <<EOF

        DELETE FROM service_entity;

        INSERT INTO service_entity(description,name,price) VALUES
        ('Hair Trim','Hair Trim',150),
        ('Haircut Premium','Haircut Premium',300),
        ('Hair Spa Deluxe','Hair Spa Deluxe',600),
        ('Beard Shave','Beard Shave',120),
        ('Beard Style Premium','Beard Style Premium',350);

        EOF

    - name: Start Frontend
      run: |
        npx serve Capstone-Frontend -l 5500 &
        sleep 10

    - name: Check Application Health
      run: |
        curl http://127.0.0.1:8081
        curl http://127.0.0.1:5500
